Repository eagles-project/mam4xx, pull requests merged in 2023-03, with the labels that each got.

#134 Remove redundant rules (bc of push mirror)
  .github/pnnl-ci/pnnl.gitlab-ci.yml
Labels: continuous integration

#136 Adds a `make memcheck` target that runs tests with Valgrind.
  CMakeLists.txt
  cmake/add_memcheck_target.cmake
Labels: testing

#142 comment unused variable in `find_renaming_pairs.cpp` to fix autotester fails
  src/validation/rename/find_renaming_pairs.cpp
Labels: bug, testing

#143 Fixing a possible race condition in uploading code coverage reports.
  .github/workflows/auto_test.yml
Labels: continuous integration
