Repository eagles-project/mam4xx, pull requests merged in 2023-08, with the labels that each got.

#225 Adds NUM_VERTICAL_LEVELS as a CMake parameter that defines mam4::nlev.
  .github/pnnl-ci/ci.sh
  .github/workflows/auto_test.yml
  CMakeLists.txt
  setup
  src/mam4xx/CMakeLists.txt
  src/mam4xx/aero_config.hpp.in
  src/mam4xx/convproc.hpp
  src/mam4xx/mo_photo.hpp
  src/mam4xx/ndrop.hpp
  src/mam4xx/wet_dep.hpp
  src/tests/CMakeLists.txt
Labels: cross-validation, build system, testing, EAMxx integration, continuous integration

#237 Add a page to the docs explaining how to get `clang-format` v14 via Homebrew
  docs/clang-format.md
  docs/development.md
  docs/dot_envrc.md
  docs/installation.md
Labels: documentation

#239 wet_dep.hpp is now installed.
  src/mam4xx/CMakeLists.txt
Labels: build system, EAMxx integration
