Repository eagles-project/mam4xx, pull requests merged in 2023-09, with the labels that each got.

#244 Adding a Sources container for storing surface and volume sources.
  src/mam4xx/aero_config.hpp.in
Labels: enhancement

#245 Adding more gas IDs to reflect E3SM's MAM4 configuration.
  src/mam4xx/aero_config.hpp.in
  src/mam4xx/aero_modes.hpp
  src/mam4xx/gasaerexch.hpp
  src/mam4xx/gasaerexch_soaexch.hpp
  src/tests/mam4_amicphys_1gridcell.cpp
  src/tests/mam4_gasaerexch_unit_tests.cpp
  src/validation/gasaerexch/skywkr_gasaerexch_timestepping.cpp
Labels: EAMxx integration

#252 Validation testing for chm_diags (from mo_chm_diags)
  src/mam4xx/mo_chm_diags.hpp
  src/validation/mo_chm_diags/CMakeLists.txt
  src/validation/mo_chm_diags/chm_diags.cpp
  src/validation/mo_chm_diags/het_diags.cpp
  src/validation/mo_chm_diags/mo_chm_diags_driver.cpp
Labels: testing

#253 Some very minor updates to documentation.
  README.md
  docs/development.md
  docs/installation.md
Labels: documentation

#254 Fixes for building mam4xx within EAMxx on GPUs
  src/mam4xx/aero_config.hpp.in
  src/mam4xx/nucleation.hpp
  src/mam4xx/rename.hpp
Labels: EAMxx integration, gpu

#255 More GPU-related fixes
  src/mam4xx/aero_config.hpp.in
  src/mam4xx/aging.hpp
  src/mam4xx/coagulation.hpp
  src/mam4xx/convproc.hpp
  src/mam4xx/nucleate_ice.hpp
  src/mam4xx/nucleation.hpp
  src/mam4xx/rename.hpp
  src/mam4xx/wet_dep.hpp
Labels: EAMxx integration, gpu
