Repository eagles-project/mam4xx, pull requests merged in 2023-11, with the labels that each got.

#261 Adding some basic data types to simplify photolysis rate calculations
  src/mam4xx/mo_photo.hpp
  src/validation/mo_photo/table_photo.cpp
Labels: cleanup

#262 Changed phtcnt from a Real to an int.
  src/mam4xx/mo_photo.hpp
Labels: bug fix

#263 Adds cmake logic to ignore -Werror flag for the Intel compiler
  src/tests/CMakeLists.txt
Labels: build system

#264 Added a single-level version of lin_strat_sfcsink.
  src/mam4xx/lin_strat_chem.hpp
Labels: EAMxx integration
